DECLARE @PROPOSTA NUMERIC(15) = 33255
DECLARE @CAMINHO VARCHAR(500) = CONCAT( 'C:\pbs\GED\PROPOSTA_',@PROPOSTA )


DECLARE @COMANDO_PASTA VARCHAR(400) = CONCAT( 'mkdir ',@CAMINHO)

EXEC master.dbo.xp_cmdshell @COMANDO_PASTA

DECLARE @GED NUMERIC(15)
DECLARE @NOME_ARQUIVO VARCHAR(500)
DECLARE @COMANDO_BCP VARCHAR(4000)

DECLARE DownloadDocs CURSOR FAST_FORWARD FOR

  SELECT B.GED , DBO.FN_SUBSTITUIR_ESPACOS( B.NOME_ARQUIVO ) AS ARQUIVO
    FROM PROPOSTAS A WITH(NOLOCK)
    JOIN GED       B WITH(NOLOCK) ON A.FORMULARIO_ORIGEM = B.FORMULARIO_ORIGEM AND A.TAB_MASTER_ORIGEM = B.TAB_MASTER_ORIGEM AND A.PROPOSTA = B.REG_MASTER_ORIGEM
   WHERE A.PROPOSTA = @PROPOSTA

OPEN DownloadDocs 

FETCH NEXT FROM DownloadDocs INTO @GED , @NOME_ARQUIVO

WHILE @@FETCH_STATUS = 0 
BEGIN

	SET @COMANDO_BCP = CONCAT( 'BCP "SELECT CONTEUDO FROM PBS_PROHOSPITAL_DADOS.DBO.GED WHERE GED = ' , @GED , '" QUERYOUT ', @CAMINHO , '\' , @NOME_ARQUIVO , ' -T -N' )

	EXEC master.dbo.xp_cmdshell @COMANDO_BCP

FETCH NEXT FROM DownloadDocs INTO @GED , @NOME_ARQUIVO

END

CLOSE DownloadDocs
DEALLOCATE DownloadDocs