CREATE FUNCTION [DBO].[UDF_MINUTOS_UTEIS] (@DT_INI DATETIME, @DT_FIM DATETIME)    
RETURNS NUMERIC(15)          
AS    
    
--DECLARE     
-- @DT_INI DATETIME = '27/04/2022 08:34:57.120',     
-- @DT_FIM DATETIME   = '03/05/2022 10:03:14.527'    
    
    
BEGIN    
 DECLARE @QT_MINUTOS BIGINT = 0    
     
 -- LOOP PARA SOMAR MINUTO A MINUTO NA DATA INICIAL ATÉ CHEGAR NA DATA FINAL    
 WHILE (@DT_INI < @DT_FIM)    
 BEGIN    
  -- VALIDA SE É UM MINUTO     
  IF (    
   DATEPART(WEEKDAY, @DT_INI) NOT IN (1)          -- DESCONSIDERA DOMINGOS    
    
   AND (DATEPART(WEEKDAY, @DT_INI) NOT IN (1,7) AND DATEPART(HOUR, @DT_INI) >= 8 AND DATEPART(HOUR, @DT_INI) < 18)    
    OR (DATEPART(WEEKDAY, @DT_INI) = (7) AND DATEPART(HOUR, @DT_INI) >= 8 AND DATEPART(HOUR, @DT_INI) < 12)  -- VALIDA SE ESTÁ ENTRE AS 8 E 12 HORAS DO SABADO    
  )    
  BEGIN    
   -- SOMA UM MINUTO NO RESULTADO    
   SELECT @QT_MINUTOS = @QT_MINUTOS + 1    
  END    
    
  -- SOMA UM MINUTO NA DATA INICIAL    
  SELECT @DT_INI = DATEADD(MINUTE, 1, @DT_INI)    
 END    
    
 -- RETORNA A QUANTIDADE TOTAL DE MINUTOS ÚTEIS    
 RETURN  @QT_MINUTOS    
END
