SET NOCOUNT ON

DECLARE @TABELA SYSNAME
DECLARE @COMANDO NVARCHAR(MAX)

IF OBJECT_ID('TEMPDB..#ERROS') IS NOT NULL DROP TABLE #ERROS
IF OBJECT_ID('TEMPDB..#COMANDOS_INSERT') IS NOT NULL DROP TABLE #COMANDOS_INSERT

CREATE TABLE #COMANDOS_INSERT ( COMANDO VARCHAR(MAX) )
CREATE TABLE #ERROS ( TABELA SYSNAME , ERRO VARCHAR(MAX) )

DECLARE LOPES_INSERT CURSOR FOR --Criar cursor com o resultado da Query

SELECT NAME FROM SYS.tables
WHERE 1=1
  AND NAME LIKE '[X-Z]%' 
  ORDER BY NAME


OPEN LOPES_INSERT --Abrir cursor

FETCH NEXT FROM LOPES_INSERT INTO @TABELA --Aponta para o primeiro registro do cursor e a cada execução vai para o próximo

WHILE @@FETCH_STATUS = 0 --Resultado do Fetch
BEGIN

BEGIN TRY

SELECT @COMANDO = DBO.FN_GERAR_INSERT(@TABELA)


INSERT INTO #COMANDOS_INSERT ( COMANDO ) SELECT  @COMANDO
END TRY
BEGIN CATCH


INSERT INTO #ERROS ( TABELA , ERRO )
VALUES ( @TABELA , ERROR_MESSAGE() )



END CATCH


FETCH NEXT FROM LOPES_INSERT INTO @TABELA --Aponta para o primeiro registro do cursor e a cada execução vai para o próximo

END

CLOSE LOPES_INSERT --Libera o select do cursor
DEALLOCATE LOPES_INSERT --Elimina as referências para o cursor


SELECT * FROM #ERROS

SELECT * FROM #COMANDOS_INSERT

SET NOCOUNT OFF